<?xml version="1.0"?>
<package format="3">
  <name>bcr_bot_with_arm</name>
  <version>0.1.0</version>
  <description>bcr_bot with 3-DOF arm and gripper</description>
  <maintainer email="sdhir5@asu.edu">Group 2</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>bcr_bot</depend>
  <depend>ros2_control</depend>
  <depend>ros2_controllers</depend>
  <depend>gz_ros2_control</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>gripper_action_controller</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
